import { useState } from "react";
import { CallUserList } from "./utils/types";

const CallListProvider = () => {
    const [callList] = useState<CallUserList[]>([
        {
            id: 1,
            name: "Meysam Jarahkar",
            lastCall: "13 oct,10:53 A.M",
            profileImage: "./personal-images/meysam-jarahkar.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 9856823520,
            call: [
                {
                    id: 1,
                    name: "Missed call",
                    lastCall: "JustNow",
                    image: "phone-missed-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 2,
                    name: "Outgoing call",
                    lastCall: "15 min ago",
                    image: "phone-outgoing-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 3,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 4,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",

                    status: "online",
                },
                {
                    id: 5,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "away",
                },
                {
                    id: 6,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 7,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 8,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 9,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
            ],
        },
        {
            id: 2,
            name: "Ayo Ogunseinde",
            lastCall: "12 oct,9:00 P.M",
            profileImage: "./personal-images/ayo-ogunseinde.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 7856258523,
            call: [
                {
                    id: 1,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "away",
                },
                {
                    id: 2,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 3,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 4,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 5,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
            ],
        },
        {
            id: 3,
            name: "Alexander Hipp",
            lastCall: "11 oct,07:48 A.M",
            profileImage: "./personal-images/alexander-hipp.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 9965230125,
            call: [
                {
                    id: 1,
                    name: "Missed call",
                    lastCall: "JustNow",
                    image: "phone-missed-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 2,
                    name: "Outgoing call",
                    lastCall: "15 min ago",
                    image: "phone-outgoing-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 3,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 4,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",

                    status: "online",
                },
            ],
        },
        {
            id: 4,
            name: "Brandon Zacharias",
            lastCall: "10 oct,12:59 P.M",
            profileImage: "./personal-images/brandon-zacharias.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 7856952350,
            call: [
                {
                    id: 1,
                    name: "Missed call",
                    lastCall: "JustNow",
                    image: "phone-missed-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 2,
                    name: "Outgoing call",
                    lastCall: "15 min ago",
                    image: "phone-outgoing-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 3,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 4,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",

                    status: "online",
                },
                {
                    id: 5,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "away",
                },
                {
                    id: 6,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "video-camera",
                    timing: "5 m 30 s",
                    status: "online",
                },
                {
                    id: 7,
                    name: "Incoming call",
                    lastCall: "15 min ago",
                    image: "phone-incoming-call.svg",
                    icon: "phone",
                    timing: "5 m 30 s",
                    status: "online",
                },
            ],
        },
        {
            id: 5,
            name: "Philip Martin",
            lastCall: "09 oct,1:26 P.M",
            profileImage: "./personal-images/philip-martin.png",
            icon: "subcall-icon.svg",
            status: "away",
            mobileNumber: 8956410012,
            call: [],
        },
        {
            id: 6,
            name: "Stephanie Liverani",
            lastCall: "09 oct,11:55 A.M",
            profileImage: "./personal-images/stephanie-liverani.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 8745823012,
            call: [],
        },
        {
            id: 7,
            name: "Tyler Nix",
            lastCall: "07 oct,4:45 P.M",
            profileImage: "./personal-images/tyler-nix.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 4589562102,
            call: [],
        },
        {
            id: 8,
            name: "Toa Heftiba",
            lastCall: "07 oct,09:00 A.M",
            profileImage: "./personal-images/toa-heftiba.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 8865210145,
            call: [],
        },
        {
            id: 9,
            name: "Bannon Morrissy",
            lastCall: "06 oct,03:39 P.M",
            profileImage: "./personal-images/bannon-morrissy.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 7985623510,
            call: [],
        },
        {
            id: 10,
            name: "Rafaella Mendes Diniz",
            lastCall: "06 oct,10:30 A.M",
            profileImage: "./personal-images/rafaella-mendes-diniz.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 8562001422,
            call: [],
        },
        {
            id: 11,
            name: "Brooke Cagle",
            lastCall: "04 oct,07:10 A.M",
            profileImage: "./personal-images/brooke-cagle.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 9016958456,
            call: [],
        },
        {
            id: 12,
            name: "Filipp Romanovski",
            lastCall: "03 oct,6:01 P.M",
            profileImage: "./personal-images/filipp-romanovski.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 9858768522,
            call: [],
        },
        {
            id: 13,
            name: "Seth Doyle",
            lastCall: "03 oct,11:45 A.M",
            profileImage: "./personal-images/seth-doyle.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 9018586810,
            call: [],
        },
        {
            id: 14,
            name: "Good Faces",
            lastCall: "02 oct,4:35 P.M",
            profileImage: "./personal-images/good-faces.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 8956102478,
            call: [],
        },
        {
            id: 15,
            name: "Harps Joseph",
            lastCall: "01 oct,12:00 A.M",
            profileImage: "./personal-images/harps-joseph.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 8569852102,
            call: [],
        },
        {
            id: 16,
            name: "Michael Dam",
            lastCall: "01 oct,09:15 A.M",
            profileImage: "./personal-images/michael-dam.png",
            icon: "subcall-icon.svg",
            status: "online",
            mobileNumber: 7982102658,
            call: [],
        },
    ]);
    return { callList };
};
export default CallListProvider;
