const GroupListData = [
        {
            id: 1,
            name: "Dream Team",
            participants: "12",
            image: "./group-images/jesse-orrico-image.png",
            cover:"./general-images/na-inho-image.png",
            archive:false,
            chat: [
                {
                    id: 1,
                    sender: {
                        id: 1,
                        firstname: "Meysam",
                        lastname: "Jarahkar",
                        email: "joiwaston@gmail.com",
                    },
                    receiver: {
                        id: 2,
                        firstname: "alex",
                        lastname: "winona",
                        email: "alenwinona@gmail.com",
                    },
                    messageType: "text",
                    deliverType: "delivered",
                    message:
                        "Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.",
                    imagename: "Wallpaper",
                    docname1: "user.png",
                    docicon: "green.svg",
                    docname2: "group.png",
                    docname3: "natural.png",
                    createdOn: "2023-10-22 10:25 AM",
                    updatedOn: "2023-10-22",
                    files: [
                        { id: 1, filename: "xyz", size: "20kb" },
                        { id: 2, filename: "New File.jpg", size: "40kb" },
                    ],
                },
                {
                    id: 2,
                    sender: {
                        id: 2,
                        firstname: "Meysam",
                        lastname: "Jarahkar",
                        email: "joiwaston@gmail.com",
                    },
                    receiver: {
                        id: 1,
                        firstname: "alex",
                        lastname: "waston",
                        email: "alenwinona@gmail.com",
                    },
                    messageType: "text",
                    deliverType: "delivered",
                    message:
                        " Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.",
                    imagename: "Wallpaper",
                    docname1: "user.png",
                    docicon: "green.svg",
                    docname2: "group.png",
                    docname3: "natural.png",
                    createdOn: "2023-10-22 10:35 AM",
                    updatedOn: "2023-10-22",
                    files: [
                        { id: 1, filename: "xyz", size: "20kb" },
                        { id: 2, filename: "New File.jpg", size: "40kb" },
                    ],
                },
                {
                    id: 3,
                    sender: {
                        id: 2,
                        firstname: "Meysam",
                        lastname: "Jarahkar",
                        email: "joiwaston@gmail.com",
                    },
                    receiver: {
                        id: 1,
                        firstname: "alex",
                        lastname: "waston",
                        email: "alenwinona@gmail.com",
                    },
                    messageType: "image",
                    deliverType: "sent",
                    message: "B",
                    imagename: "Wallpaper",
                    docname1: "user.png",
                    docicon: "green.svg",
                    docname2: "group.png",
                    docname3: "natural.png",
                    createdOn: "2023-10-22 10 : 40 AM",
                    updatedOn: "2023-10-22",
                    files: [{ id: 1, filename: "xyz", size: "21kb" }],
                },
                {
                    id: 4,
                    sender: {
                        id: 1,
                        firstname: "Meysam",
                        lastname: "Jarahkar",
                        email: "joiwaston@gmail.com",
                    },
                    receiver: {
                        id: 2,
                        firstname: "alex",
                        lastname: "winona",
                        email: "alenwinona@gmail.com",
                    },
                    messageType: "image",
                    deliverType: "sent",
                    message: "A",
                    imagename: "Wallpaper",
                    docname1: "user.png",
                    docicon: "green.svg",
                    docname2: "group.png",
                    docname3: "natural.png",
                    createdOn: "2023-10-22 10:50 AM",
                    updatedOn: "2023-10-22",
                    files: [{ id: 1, filename: "xyz", size: "21kb" }],
                },

                {
                    id: 5,
                    sender: {
                        id: 1,
                        firstname: "Meysam",
                        lastname: "Jarahkar",
                        email: "joiwaston@gmail.com",
                    },
                    receiver: {
                        id: 2,
                        firstname: "alex",
                        lastname: "winona",
                        email: "alenwinona@gmail.com",
                    },
                    messageType: "Document",
                    deliverType: "sent",
                    message: "3 MB",
                    imagename: "Wallpaper.png",
                    docname1: "user.png",
                    docicon: "green.svg",
                    docname2: "group.png",
                    docname3: "natural.png",
                    createdOn: "2023-10-22 11:00 AM",
                    updatedOn: "2023-10-22",
                    files: [
                        { id: 1, filename: "xyz", size: "25kb" },
                        { id: 2, filename: "New File.jpg", size: "40kb" },
                        { id: 3, filename: "New File.jpg", size: "40kb" },
                        { id: 4, filename: "New File.jpg", size: "40kb" },
                        { id: 5, filename: "New File.jpg", size: "40kb" },
                    ],
                },

                {
                    id: 6,
                    sender: {
                        id: 2,
                        firstname: "Meysam",
                        lastname: "Jarahkar",
                        email: "joiwaston@gmail.com",
                    },
                    receiver: {
                        id: 1,
                        firstname: "alex",
                        lastname: "Waston",
                        email: "alenwinona@gmail.com",
                    },
                    messageType: "Document",
                    deliverType: "sent",
                    message: "3 MB",
                    imagename: "Wallpaper.png",
                    docname1: "user.png",
                    docicon: "green.svg",
                    docname2: "group.png",
                    docname3: "natural.png",
                    createdOn: "2023-10-22 11 : 20 AM",
                    updatedOn: "2023-10-22",
                    files: [{ id: 1, filename: "xyz", size: "25kb" }],
                },
            ],
            GroupList: [
                {
                    id: 100,
                    name: "Oliver Ragfelt",
                    image: "./images/oliver-ragfelt.png",
                    role: "admin",
                    lastMessage: "hey there i am available",
                    createdOn: "2:00 pm",
                    status: "online",
    
                },
                {
                    id: 1,
                    name: "Meysam Jarahkar",
                    image: "./personal-images/meysam-jarahkar.png",
                    role: "admin",
                    lastMessage: "hey there i am available",
                    createdOn: "2:00 pm",
                    status: "online",

                },
                {
                    id: 3,
                    name: "Alexander Hipp",
                    image: "./personal-images/alexander-hipp.png",
                    role: "admin",
                    lastMessage: "hey there i am available",
                    createdOn: "2:10 pm",
                    status: "online",
                    
                },
                {
                    id: 4,
                    name: "Brandon Zacharias",
                    image: "./personal-images/brandon-zacharias.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "2:20 pm",
                    status: "away",
                    
                },
                {
                    id: 6,
                    name: "Stephanie Liverani",
                    image: "./personal-images/stephanie-liverani.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "2:30 pm",
                    status: "offline",
                    
                },
                {
                    id: 7,
                    name: "Tyler Nix",
                    image: "./personal-images/tyler-nix.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "2:40 pm",
                    status: "away",
                    
                },
                {
                    id: 8,
                    name: "Toa Heftiba",
                    image: "./personal-images/toa-heftiba.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "2:50 pm",
                    status: "offline",
                    
                },
                {
                    id: 9,
                    name: "Bannon Morrissy",
                    image: "./personal-images/bannon-morrissy.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "3:00 pm",
                    status: "away",
                    
                },
                {
                    id: 10,
                    name: "Rafaella Mendes Diniz",
                    image: "./personal-images/rafaella-mendes-diniz.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "3:10 pm",
                    status: "online",
                    
                },
                {
                    id: 11,
                    name: "Brooke Cagle",
                    image: "./personal-images/brooke-cagle.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "3:20 pm",
                    status: "offline",
                    
                },
                {
                    id: 12,
                    name: "Filipp Romanovski",
                    image: "./personal-images/filipp-romanovski.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "3:30 pm",
                    status: "away",
                    
                },
                {
                    id: 14,
                    name: "Good Faces",
                    image: "./personal-images/good-faces.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "3:40 pm",
                    status: "offline",
                    
                },
                {
                    id: 15,
                    name: "Harps Joseph",
                    image: "./personal-images/harps-joseph.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "3:50 pm",
                    status: "online",
                    
                },
            ],
        },
        {
            id: 2,
            name: "Daybreak",
            participants: "10",
            image: "./group-images/robin-van-holst-image.png",
            cover:"./general-images/ahmed-nishaath-image.png",
            archive:false,
            chat: [
            {
                id: 1,
                sender: {
                    id: 1,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "text",
                deliverType: "delivered",
                message:
                    "Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10:25 AM",
                updatedOn: "2023-10-22",
                files: [
                    { id: 1, filename: "xyz", size: "20kb" },
                    { id: 2, filename: "New File.jpg", size: "40kb" },
                ],
            },
            {
                id: 2,
                sender: {
                    id: 2,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 1,
                    firstname: "alex",
                    lastname: "waston",
                    email: "alenwinona@gmail.com",
                },
                messageType: "text",
                deliverType: "delivered",
                message:
                    " Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10:35 AM",
                updatedOn: "2023-10-22",
                files: [
                    { id: 1, filename: "xyz", size: "20kb" },
                    { id: 2, filename: "New File.jpg", size: "40kb" },
                ],
            },
            {
                id: 3,
                sender: {
                    id: 2,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 1,
                    firstname: "alex",
                    lastname: "waston",
                    email: "alenwinona@gmail.com",
                },
                messageType: "image",
                deliverType: "sent",
                message: "B",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10 : 40 AM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "xyz", size: "21kb" }],
            },
            {
                id: 4,
                sender: {
                    id: 1,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "image",
                deliverType: "sent",
                message: "A",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10:50 AM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "xyz", size: "21kb" }],
            },

            {
                id: 5,
                sender: {
                    id: 1,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "Document",
                deliverType: "sent",
                message: "3 MB",
                imagename: "Wallpaper.png",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 11:00 AM",
                updatedOn: "2023-10-22",
                files: [
                    { id: 1, filename: "xyz", size: "25kb" },
                    { id: 2, filename: "New File.jpg", size: "40kb" },
                    { id: 3, filename: "New File.jpg", size: "40kb" },
                    { id: 4, filename: "New File.jpg", size: "40kb" },
                    { id: 5, filename: "New File.jpg", size: "40kb" },
                ],
            },

            {
                id: 6,
                sender: {
                    id: 2,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 1,
                    firstname: "alex",
                    lastname: "Waston",
                    email: "alenwinona@gmail.com",
                },
                messageType: "Document",
                deliverType: "sent",
                message: "3 MB",
                imagename: "Wallpaper.png",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 11 : 20 AM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "xyz", size: "25kb" }],
            },
        ],
            GroupList: [
                {
                    id: 100,
                    name: "Oliver Ragfelt",
                    image: "./images/oliver-ragfelt.png",
                    role: "admin",
                    lastMessage: "hey there i am available",
                    createdOn: "2:00 pm",
                    status: "online",
    
                },
                {
                    id: 1,
                    name: "Meysam Jarahkar",
                    image: "./personal-images/meysam-jarahkar.png",
                    role: "admin",
                    lastMessage: "hey there i am available",
                    createdOn: "4:00 pm",
                    status: "online",
                },
                {
                    id: 3,
                    name: "Alexander Hipp",
                    image: "./personal-images/alexander-hipp.png",
                    role: "admin",
                    lastMessage: "hey there i am available",
                    createdOn: "4:10 pm",
                    status: "offline",
                },
                {
                    id: 4,
                    name: "Brandon Zacharias",
                    image: "./personal-images/brandon-zacharias.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "4:20 pm",
                    status: "away",
                },
                {
                    id: 6,
                    name: "Stephanie Liverani",
                    image: "./personal-images/stephanie-liverani.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "4:30 pm",
                    status: "online",
                },
                {
                    id: 7,
                    name: "Tyler Nix",
                    image: "./personal-images/tyler-nix.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "4:40 pm",
                    status: "away",
                },
                {
                    id: 8,
                    name: "Toa Heftiba",
                    image: "./personal-images/toa-heftiba.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "5:00 pm",
                    status: "online",
                },
                {
                    id: 9,
                    name: "Bannon Morrissy",
                    image: "./personal-images/bannon-morrissy.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "5:10 pm",
                    status: "online",    
            },
                {
                    id: 10,
                    name: "Rafaella Mendes Diniz",
                    image: "./personal-images/rafaella-mendes-diniz.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "5:20 pm",
                    status: "offline",
                },
                {
                    id: 11,
                    name: "Brooke Cagle",
                    image: "./personal-images/brooke-cagle.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "5:30 pm",
                    status: "offline",
                },
                {
                    id: 12,
                    name: "Filipp Romanovski",
                    image: "./personal-images/filipp-romanovski.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "5:40 pm",
                    status: "away",
                },
            ],
        },
        {
            id: 3,
            name: "Universal Signals",
            participants: "7",
            image: "./group-images/jaz-king-image.png",
            cover:"./general-images/christian-joudrey-image.png",
            archive:false,
            chat: [],
            GroupList: [
                {
                    id: 1,
                    name: "Meysam Jarahkar",
                    image: "./personal-images/meysam-jarahkar.png",
                    role: "admin",
                    lastMessage: "hey there i am available",
                    createdOn: "6:00 pm",
                    status: "online",
                },
                {
                    id: 3,
                    name: "Alexander Hipp",
                    image: "./personal-images/alexander-hipp.png",
                    role: "admin",
                    lastMessage: "hey there i am available",
                    createdOn: "6:10 pm",
                    status: "offline",
                },
                {
                    id: 4,
                    name: "Brandon Zacharias",
                    image: "./personal-images/brandon-zacharias.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "6:20 pm",
                    status: "online",
                },
                {
                    id: 6,
                    name: "Stephanie Liverani",
                    image: "./personal-images/stephanie-liverani.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "6:30 pm",
                    status: "offline",
                },
                {
                    id: 7,
                    name: "Tyler Nix",
                    image: "./personal-images/tyler-nix.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "6:40 pm",
                    status: "away",
                },
                {
                    id: 11,
                    name: "Brooke Cagle",
                    image: "./personal-images/brooke-cagle.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "6:50 pm",
                    status: "offline",
                },
                {
                    id: 12,
                    name: "Filipp Romanovski",
                    image: "./personal-images/filipp-romanovski.png",
                    role: "user",
                    lastMessage: "hey there i am available",
                    createdOn: "6:55 pm",
                    status: "away",
                },
            ],
        },
        {
            id: 4,
            name: "Connect Collective",
            participants: "13",
            image: "./group-images/matt-c-image.png",
            cover:"./general-images/david-marcu-image.png",
            archive:false,
            chat: [],
            GroupList: [
                {
                id: 16,
                name: "Michael Dam",
                image: "./personal-images/michael-dam.png",
                role: "user",
                lastMessage: "hey there i am available",
                createdOn: "6:55 pm",
                status: "away",
            },
            {
                id: 100,
                name: "Oliver Ragfelt",
                image: "./images/oliver-ragfelt.png",
                role: "admin",
                lastMessage: "hey there i am available",
                createdOn: "2:00 pm",
                status: "online",

            },
        ],
        },
        {
            id: 5,
            name: "News Spectator",
            participants: "9",
            image: "./group-images/roman-kraft-image.png",
            cover:"./general-images/dino-reichmuth-image.png",
            archive:false,
            chat: [],
            GroupList: [],
        },
        {
            id: 6,
            name: "Key Frequency",
            participants: "4",
            image: "./group-images/anne-nygård-image.png",
            cover:"./general-images/jordan-mcQueen-image.png",
            archive:false,
            chat: [],
            GroupList: [],
        },
        {
            id: 7,
            name: "Voice it",
            participants: "3",
            image: "./group-images/jason-rosewell-image.png",
            cover:"./general-images/jorgen-hendriksen-image.png",
            archive:false,
            chat: [],
            GroupList: [],
        },
        {
            id: 8,
            name: "The Family Gang",
            participants: "14",
            image: "./group-images/nathan-dumlao-image.png",
            cover:"./general-images/mickey-oneil-image.png",
            archive:true,
            chat: [],
            GroupList: [],
        },
        {
            id: 9,
            name: "So Called Engineers",
            participants: "17",
            image: "./group-images/tool-inc-image.png",
            cover:"./general-images/na-inho-image.png",
            archive:false,
            chat: [],
            GroupList: [],
        },
        {
            id: 10,
            name: "Roast Club",
            participants: "13",
            image: "./group-images/flash-dantz-image.png",
            cover:"./general-images/nina-plobner-image.png",
            archive:false,
            chat: [],
            GroupList: [],
        },
        {
            id: 11,
            name: "Travel Buddies",
            participants: "7",
            image: "./group-images/dario-brönnimann-image.png",
            cover:"./general-images/v2osk-image.png",
            archive:true,
            chat: [],
            GroupList: [],
        },
        {
            id: 12,
            name: "Selfie Dump",
            participants: "15",
            image: "./group-images/nate-johnston-image.png",
            cover:"./general-images/vincentiu-solomon-image.png",
            archive:false,
            chat: [],
            GroupList: [],
        },
        {
            id: 13,
            name: "Avengers",
            participants: "6",
            image: "./group-images/mulyadi-image.png",
            cover:"./general-images/jordan-mcQueen-image.png",
            archive:true,
            chat: [],
            GroupList: [],
        },
        {
            id: 14,
            name: "Gaming Buddies",
            participants: "17",
            image: "./group-images/carl-raw-images.png",
            cover:"./general-images/v2osk-image.png",
            archive:false,
            chat: [],
            GroupList: [],
        },
        {
            id: 15,
            name: "Crazy People Inside",
            participants: "15",
            image: "./group-images/saeed-karimi-image.png",
            cover:"./general-images/david-marcu-image.png",
            archive:true,
            chat: [],
            GroupList: [],
        },{
            id: 16,
            name: "The Squad",
            participants: "09",
            image: "./group-images/austin-distel-image.png",
            cover:"./general-images/christian-joudrey-image.png",
            archive:false,
            chat: [],
            GroupList: [],
        },{
            id: 17,
            name: "Tech Geeks",
            participants: "05",
            image: "./group-images/liam-tucker-image.png",
            cover:"./general-images/jordan-mcQueen-image.png",
            archive:true,
            chat: [],
            GroupList: [],
        },{
            id: 18,
            name: "Dreamers",
            participants: "10",
            image: "./group-images/rob-walsh-image.png",
            cover:"./general-images/mickey-oneil-image.png",
            archive:false,
            chat: [],
            GroupList: [],
        },
    ]
export default GroupListData;
