const userListData = [
    {
        id: 1,
        name: "Meysam Jarahkar",
        createdOn: "2:30 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/meysam-jarahkar.png",
        email: "meysam@gmail.com",
        icon: "./images/green.svg",
        msg: 2,
        read: false,
        status: "online",
        blocked: true,
        favorite: true,
        cover: "./general-images/na-inho-image.png",
        archive: false,
        chat: [
            {
                id: 1,
                sender: {
                    id: 1,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "text",
                deliverType: "delivered",
                message:
                    "Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10:25 AM",
                updatedOn: "2023-10-22",
                files: [
                    { id: 1, filename: "xyz", size: "20kb" },
                    { id: 2, filename: "New File.jpg", size: "40kb" },
                ],
            },
            {
                id: 2,
                sender: {
                    id: 2,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 1,
                    firstname: "alex",
                    lastname: "waston",
                    email: "alenwinona@gmail.com",
                },
                messageType: "text",
                deliverType: "delivered",
                message:
                    " Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10:35 AM",
                updatedOn: "2023-10-22",
                files: [
                    { id: 1, filename: "xyz", size: "20kb" },
                    { id: 2, filename: "New File.jpg", size: "40kb" },
                ],
            },
            {
                id: 3,
                sender: {
                    id: 2,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 1,
                    firstname: "alex",
                    lastname: "waston",
                    email: "alenwinona@gmail.com",
                },
                messageType: "image",
                deliverType: "sent",
                message: "B",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10 : 40 AM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "xyz", size: "21kb" }],
            },
            {
                id: 4,
                sender: {
                    id: 1,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "image",
                deliverType: "sent",
                message: "A",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10:50 AM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "xyz", size: "21kb" }],
            },

            {
                id: 5,
                sender: {
                    id: 1,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "Document",
                deliverType: "sent",
                message: "3 MB",
                imagename: "Wallpaper.png",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 11:00 AM",
                updatedOn: "2023-10-22",
                files: [
                    { id: 1, filename: "xyz", size: "25kb" },
                    { id: 2, filename: "New File.jpg", size: "40kb" },
                    { id: 3, filename: "New File.jpg", size: "40kb" },
                    { id: 4, filename: "New File.jpg", size: "40kb" },
                    { id: 5, filename: "New File.jpg", size: "40kb" },
                ],
            },

            {
                id: 6,
                sender: {
                    id: 2,
                    firstname: "Meysam",
                    lastname: "Jarahkar",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 1,
                    firstname: "alex",
                    lastname: "Waston",
                    email: "alenwinona@gmail.com",
                },
                messageType: "Document",
                deliverType: "sent",
                message: "3 MB",
                imagename: "Wallpaper.png",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 11 : 20 AM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "xyz", size: "25kb" }],
            },
            {
                id: 7,
                sender: {
                    id: 2,
                    firstname: "Oliver",
                    lastname: "Ragfelt",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 1,
                    firstname: "alex",
                    lastname: "waston",
                    email: "alenwinona@gmail.com",
                },
                messageType: "text",
                deliverType: "delivered",
                message:
                    " Hey Alex, how's your day going ? let me know when you are available for meeting, thanks.",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10:35 AM",
                updatedOn: "2023-10-22",
                files: [
                    { id: 1, filename: "xyz", size: "20kb" },
                    { id: 2, filename: "New File.jpg", size: "40kb" },
                ],
            },
        ],
    },
    {
        id: 2,
        name: "Ayo Ogunseinde",
        email: "ayo@gmail.com",
        createdOn: "2:30 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/ayo-ogunseinde.png",
        icon: "./images/green.svg",
        status: "online",
        blocked: true,
        favorite: true,
        cover: "./general-images/ahmed-nishaath-image.png",
        archive: true,
        chat: [
            {
                id: 1,
                sender: {
                    id: 1,
                    firstname: "Ayo",
                    lastname: "Ogunseinde",
                    email: "joiwaston@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "text",
                deliverType: "sent",
                message: "A",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 10:25 AM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "xyz", size: "26kb" }],
            },
        ],
    },
    {
        id: 3,
        name: "Alexander Hipp",
        email: "alexander@gmail.com",
        createdOn: "2:40 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/alexander-hipp.png",
        icon: "./images/green.svg",
        status: "online",
        blocked: true,
        favorite: true,
        cover: "./general-images/christian-joudrey-image.png",
        archive: false,
        chat: [
            {
                id: 1,
                sender: {
                    id: 1,
                    firstname: "Alexander",
                    lastname: "Hipp",
                    email: "alexander@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "text",
                deliverType: "sent",
                message: "How's it going? Long time no see!",
                imagename: "Wallpaper",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 11:10 AM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "document.pdf", size: "100kb" }],
            },
            {
                id: 2,
                sender: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                receiver: {
                    id: 1,
                    firstname: "Alexander",
                    lastname: "Hipp",
                    email: "alexander@gmail.com",
                },
                messageType: "image",
                deliverType: "sent",
                message: "Check this out!",
                imagename: "image.jpg",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 11:20 AM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "image.jpg", size: "500kb" }],
            },
        ],
    },
    {
        id: 4,
        name: "Brandon Zacharias",
        email: "brandon@gmail.com",
        createdOn: "2:50 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/brandon-zacharias.png",
        icon: "./images/green.svg",
        status: "away",
        blocked: true,
        favorite: false,
        cover: "./general-images/david-marcu-image.png",
        archive: false,
        chat: [
            {
                id: 1,
                sender: {
                    id: 1,
                    firstname: "Sven",
                    lastname: "Piper",
                    email: "sven@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "text",
                deliverType: "read",
                message: "Are you free this weekend?",
                imagename: "nature.jpg",
                docname1: "user.png",
                docicon: "red.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 12:00 PM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "schedule.pdf", size: "50kb" }],
            },
            {
                id: 2,
                sender: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                receiver: {
                    id: 1,
                    firstname: "Sven",
                    lastname: "Piper",
                    email: "sven@gmail.com",
                },
                messageType: "text",
                deliverType: "read",
                message: "Yes, let's plan something.",
                imagename: "city.jpg",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 12:10 PM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "itinerary.pdf", size: "75kb" }],
            },
        ],
    },
    {
        id: 5,
        name: "Philip Martin",
        email: "philip@gmail.com",
        createdOn: "2:60 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/philip-martin.png",
        icon: "./images/green.svg",
        status: "online",
        blocked: false,
        favorite: false,
        cover: "./general-images/dino-reichmuth-image.png",
        archive: false,
        chat: [
            {
                id: 1,
                sender: {
                    id: 1,
                    firstname: "Heidi",
                    lastname: "Sandstrom",
                    email: "heidi@gmail.com",
                },
                receiver: {
                    id: 2,
                    firstname: "alex",
                    lastname: "winona",
                    email: "alenwinona@gmail.com",
                },
                messageType: "document",
                deliverType: "delivered",
                message: "Here is the report for Q3.",
                imagename: "report.pdf",
                docname1: "user.png",
                docicon: "green.svg",
                docname2: "group.png",
                docname3: "natural.png",
                createdOn: "2023-10-22 1:00 PM",
                updatedOn: "2023-10-22",
                files: [{ id: 1, filename: "report.pdf", size: "1MB" }],
            },
        ],
    },
    {
        id: 6,
        name: "Stephanie Liverani",
        email: "stephanie@gmail.com",
        createdOn: "3:00 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/stephanie-liverani.png",
        icon: "./images/yellowdot.svg",
        status: "offline",
        blocked: false,
        favorite: true,
        cover: "./general-images/jordan-mcQueen-image.png",
        archive: false,
        chat: [],
    },

    {
        id: 7,
        name: "Tyler Nix",
        email: "tyler@gmail.com",
        createdOn: "3:10 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/tyler-nix.png",
        icon: "./images/reddot.svg",
        status: "away",
        blocked: false,
        favorite: false,
        cover: "./general-images/jorgen-hendriksen-image.png",
        archive: false,
        chat: [],
    },
    {
        id: 8,
        name: "Toa Heftiba",
        email: "toa@gmail.com",
        createdOn: "3:20 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/toa-heftiba.png",
        icon: "./images/reddot.svg",
        status: "away",
        blocked: true,
        favorite: true,
        cover: "./general-images/mickey-oneil-image.png",
        archive: false,
        chat: [],
    },
    {
        id: 9,
        name: "Bannon Morrissy",
        email: "bannon@gmail.com",
        createdOn: "3:30 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/bannon-morrissy.png",
        icon: "./images/yellowdot.svg",
        status: "offline",
        blocked: false,
        favorite: false,
        cover: "./general-images/na-inho-image.png",
        archive: false,
        chat: [],
    },
    {
        id: 10,
        name: "Rafaella Mendes Diniz",
        email: "rafaella@gmail.com",
        createdOn: "3:40 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/rafaella-mendes-diniz.png",
        icon: "./images/yellowdot.svg",
        status: "online",
        blocked: true,
        favorite: true,
        cover: "./general-images/nina-plobner-image.png",
        archive: false,
        chat: [],
    },
    {
        id: 11,
        name: "Brooke Cagle",
        email: "brooke@gmail.com",
        createdOn: "3:50 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/brooke-cagle.png",
        icon: "./images/yellowdot.svg",
        status: "offline",
        blocked: false,
        favorite: true,
        cover: "./general-images/v2osk-image.png",
        archive: true,
        chat: [],
    },
    {
        id: 12,
        name: "Filipp Romanovski",
        email: "filipp@gmail.com",
        createdOn: "3:60 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/filipp-romanovski.png",
        icon: "./images/yellowdot.svg",
        status: "away",
        blocked: true,
        favorite: false,
        cover: "./general-images/vincentiu-solomon-image.png",
        archive: true,
        chat: [],
    },
    {
        id: 13,
        name: "Seth Doyle",
        email: "seth@gmail.com",
        createdOn: "4:00 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/seth-doyle.png",
        icon: "./images/yellowdot.svg",
        status: "offline",
        blocked: false,
        favorite: true,
        cover: "./general-images/jordan-mcQueen-image.png",
        archive: false,
        chat: [],
    },
    {
        id: 14,
        name: "Good Faces",
        email: "good@gmail.com",
        createdOn: "4:10 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/good-faces.png",
        icon: "./images/yellowdot.svg",
        status: "away",
        blocked: false,
        favorite: false,
        cover: "./general-images/v2osk-image.png",
        archive: true,
        chat: [],
    },
    {
        id: 15,
        name: "Harps Joseph",
        email: "harps@gmail.com",
        createdOn: "4:20 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/harps-joseph.png",
        icon: "./images/yellowdot.svg",
        status: "offline",
        blocked: true,
        favorite: false,
        cover: "./general-images/david-marcu-image.png",
        archive: false,
        chat: [],
    },
    {
        id: 16,
        name: "Michael Dam",
        email: "michael@gmail.com",
        createdOn: "4:30 pm",
        lastMessage: "hey there i am available",
        image: "./personal-images/michael-dam.png",
        icon: "./images/yellowdot.svg",
        status: "away",
        blocked: false,
        favorite: true,
        cover: "./general-images/christian-joudrey-image.png",
        archive: false,
        chat: [],
    },
];
export default userListData;
